#!/bin/sh
#
# PROVIDE: tw_recorder
# REQUIRE: LOGIN NETWORKING syslogd
# KEYWORD: shutdown
#
# FreeBSD-rc.d-Pendant zu debian/tw-recorder.service. Installation und
# Aktivierung siehe README.md ("FreeBSD"). Wird bewusst NICHT automatisch
# aktiviert:
#
#   sysrc tw_recorder_enable=YES
#   service tw-recorder start
#
# Variablen (in /etc/rc.conf bzw. per sysrc):
#   tw_recorder_enable
#       YES zum Aktivieren (Standard: NO)
#   tw_recorder_runas
#       Dienstuser (Standard: tw-recorder). Bewusst nicht tw_recorder_user:
#       damit wuerde rc.subr schon daemon(8) selbst per su als dieser
#       User starten, daemon -u braucht aber root.
#   tw_recorder_command
#       Pfad zum Programm (Standard: /usr/local/bin/tw-recorder)
#   tw_recorder_args
#       Zusaetzliche Argumente nach -D (Standard: leer). Bewusst nicht
#       tw_recorder_flags: das haengt rc.subr an daemon(8) statt an
#       tw-recorder an.
#   tw_recorder_env
#       Umgebungsvariablen, z.B. "LOG_LEVEL=DEBUG" (wertet rc.subr aus)
#
# tw-recorder daemonisiert sich nicht selbst (laeuft im Vordergrund wie unter
# systemd Type=simple) - daemon(8) uebernimmt Forken, Userwechsel (-u ruft
# initgroups() auf, damit greift auch die media-pipeline-Zusatzgruppe wie
# SupplementaryGroups= in der systemd-Unit) und Neustart bei Absturz (-r,
# wie Restart=on-failure). -S leitet stdout/stderr an syslog weiter: ohne
# /proc erkennt die App keinen laufenden syslogd und loggt nur auf stdout.
# SIGTERM an den daemon(8)-Supervisor wird an den Prozess weitergereicht.

. /etc/rc.subr

name="tw_recorder"
rcvar="tw_recorder_enable"

load_rc_config $name

: ${tw_recorder_enable:="NO"}
: ${tw_recorder_runas:="tw-recorder"}
: ${tw_recorder_command:="/usr/local/bin/tw-recorder"}
: ${tw_recorder_args:=""}

pidfile="/var/run/${name}.pid"
procname="/usr/sbin/daemon"
command="/usr/sbin/daemon"
command_args="-f -S -T tw-recorder -r -R 5 -P ${pidfile} -u ${tw_recorder_runas} ${tw_recorder_command} -D ${tw_recorder_args}"

run_rc_command "$1"
